Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/user.rb, app/views/thanks.html.erb, app/views/users/new.html.erb, config/routes.rb, db/migrate/20151103195435_create_users.rb, db/schema.rb
Added user migration and a user can signup
=> Create student migrations

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/foundation_and_overrides.scss, app/views/layouts/application.html.erb, config/environments/production.rb, config/initializers/assets.rb
=> Add foundation

app/assets/javascripts/studentToggle.js, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, app/views/users/new.html.erb
Add javascript to the signup page when declaring if your a student or not
=> Clean up user new page

app/assets/javascripts/studentToggle.js, app/assets/stylesheets/application.scss, app/views/users/new.html.erb
Fixed radio button issue 
Fixed javascript toggle
=> Fix toggle

app/assets/stylesheets/application.scss, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb
=> Add footer complete

app/assets/javascripts/studentToggle.js, app/assets/stylesheets/application.scss, app/views/layouts/_header.html.erb, app/views/users/new.html.erb, db/schema.rb
=> Program search

app/controllers/advisors_controller.rb, app/controllers/users_controller.rb, app/models/advisor.rb, app/models/user.rb, app/views/advisors/edit.html.erb, app/views/advisors/new.html.erb, db/schema.rb
Update advisor info is working
=> Update advisor info working

app/assets/stylesheets/application.scss, app/views/advisors/show.html.erb
CSS changes to advisor profile page
=> Advisor profile page

app/controllers/advisors_controller.rb, app/controllers/carts_controller.rb, app/controllers/potential_appointments_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/cart.rb, app/models/potential_appointment.rb, app/views/advisors/show.html.erb, app/views/carts/show.html.erb, app/views/layouts/_header.html.erb, config/routes.rb, db/migrate/20151116165234_create_potential_appointments.rb, db/migrate/20151117230032_add_checked_out_to_carts.rb, db/migrate/20151118023033_create_potential_appointments_carts.rb, db/migrate/20151118023345_remove_advisor_from_potential_appointments.rb, db/schema.rb
Creating Cart for user to add advisor appointments inside of
=> Create potential appointments

Gemfile, Gemfile.lock
=> Add a gem called daemon to the gem file

app/assets/stylesheets/application.scss, app/controllers/potential_appointments_controller.rb, app/models/potential_appointment.rb, app/views/potential_appointments/new.html.erb, db/schema.rb
=> Css advisor pages

app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/views/advisors/show.html.erb
=> Add correct time format

app/assets/stylesheets/application.scss, app/assets/stylesheets/buttons.scss, app/controllers/carts_controller.rb, app/views/advisors/show.html.erb, app/views/carts/show.html.erb, app/views/layouts/_header.html.erb, app/views/potential_appointments/new.html.erb
Add css to cart and potential new appointment
=> Css potential appointment new

app/assets/stylesheets/application.scss, app/controllers/orders_controller.rb, app/models/cart.rb, app/models/order.rb, app/views/advisors/show.html.erb, app/views/carts/show.html.erb, app/views/orders/new.html.erb
Need to add logic if 2 people order the same appointment
=> Css new order page

app/controllers/application_controller.rb, app/controllers/potential_appointments_controller.rb, app/models/potential_appointment.rb, app/views/advisors/show.html.erb, app/views/potential_appointments/edit.html.erb
Edit and update potential appointments
=> Create edit appointments

app/assets/stylesheets/application.scss, app/views/advisors/show.html.erb, app/views/layouts/_header.html.erb
Need to fix header for mobile view
=> Production deployment

app/assets/stylesheets/application.scss, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/show.html.erb
=> Clean up for mobile view

app/views/layouts/_header.html.erb
Remove active
Change Advisors to network
=> Fix header

app/assets/stylesheets/application.scss, app/controllers/password_resets_controller.rb, app/controllers/users_controller.rb, app/mailers/advisor_mailer.rb, app/mailers/user_mailer.rb, app/models/advisor.rb, app/models/user.rb, app/views/advisor_mailer/password_reset.html.erb, app/views/advisor_mailer/password_reset.text.erb, app/views/layouts/_header.html.erb, app/views/password_resets/edit.html.erb, app/views/password_resets/new.html.erb, app/views/sessions/new.html.erb, app/views/user_mailer/password_reset.html.erb, app/views/user_mailer/password_reset.text.erb, config/environments/development.rb, config/environments/production.rb, db/migrate/20151216183559_add_password_reset_to_users.rb, db/migrate/20151216203949_add_password_reset_to_advisors.rb, db/schema.rb
=> Reset password

app/assets/stylesheets/application.scss, app/views/advisors/index.html.erb, app/views/welcome/about.html.erb
=> Get pics on aws

app/assets/javascripts/aboutPhonePopup.js, app/assets/javascripts/toggle.js, app/assets/stylesheets/application.scss, app/views/welcome/_popup_categories_phone.html.erb, app/views/welcome/_popup_locations_phone.html.erb, app/views/welcome/_popup_question_fees.html.erb, app/views/welcome/_popup_question_phone.html.erb, app/views/welcome/_popup_years_phone.html.erb, app/views/welcome/about.html.erb, db/migrate/20160127000556_drop_advisors_categories.rb
=> About changes 2

app/views/advisor_mailer/email_verification.html.erb, app/views/user_mailer/email_verification.html.erb
=> Fix email template

app/assets/javascripts/toggle.js, app/assets/stylesheets/application.scss, app/controllers/comments_controller.rb, app/views/welcome/_comments_edit_form.html.erb, app/views/welcome/index.html.erb
=> Home page changes

config/environments/production.rb
=> Revert "comment out paypal"
